### ISSUE TITLE
Fix _doc bug

### ISSUE THREAD

**Issue by bw-allardvanhelbergen** [bw-allardvanhelbergen/go#102]
createOrUpdateUser() seems to return null once in a while...

From live logs:
2015-06-04T08:59:20.746Z - error: uncaughtException: Cannot read property '_doc' of null date=Thu Jun 04 2015 08:59:20 GMT+0000 (UTC), pid=16192, uid=2044, gid=2044, cwd=/home/brandwatch/go, execPath=/home/brandwatch/.nvm/v0.10.33/bin/n
ode, version=v0.10.33, argv=[/home/brandwatch/.nvm/v0.10.33/bin/node, /home/brandwatch/go], rss=100614144, heapTotal=87993600, heapUsed=46218640, loadavg=[0.0029296875, 0.0146484375, 0.04541015625], uptime=3283428.054689778, trace=[colu
mn=53, file=/home/brandwatch/go/app/controllers/userController.js, function=null, line=35, method=null, native=false, column=54, file=/home/brandwatch/go/node_modules/q/q.js, function=_fulfilled, line=794, method=null, native=false, col
umn=30, file=/home/brandwatch/go/node_modules/q/q.js, function=self.promiseDispatch.done, line=823, method=promiseDispatch.done, native=false, column=13, file=/home/brandwatch/go/node_modules/q/q.js, function=Promise.promise.promiseDisp
atch, line=756, method=promise.promiseDispatch, native=false, column=44, file=/home/brandwatch/go/node_modules/q/q.js, function=null, line=564, method=null, native=false, column=17, file=/home/brandwatch/go/node_modules/q/q.js, function
=flush, line=110, method=null, native=false, column=13, file=node.js, function=process._tickCallback, line=419, method=_tickCallback, native=false], stack=[TypeError: Cannot read property '_doc' of null,     at /home/brandwatch/go/app/c
ontrollers/userController.js:35:53,     at _fulfilled (/home/brandwatch/go/node_modules/q/q.js:794:54),     at self.promiseDispatch.done (/home/brandwatch/go/node_modules/q/q.js:823:30),     at Promise.promise.promiseDispatch (/home/bra
ndwatch/go/node_modules/q/q.js:756:13),     at /home/brandwatch/go/node_modules/q/q.js:564:44,     at flush (/home/brandwatch/go/node_modules/q/q.js:110:17),     at process._tickCallback (node.js:419:13)]

**Comment by bw-allardvanhelbergen** [comment]
Introduced the issue through update of MongoDb and Mongoose in https://github.com/bw-allardvanhelbergen/go/commit/a1c56798e8553a8673d4f78d0d203969167ee9c6.

See:
https://github.com/Automattic/mongoose/issues/2262
and
http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate 
"new: bool - if true, return the modified document rather than the original. defaults to false (changed in 4.0)"

**Comment by bw-allardvanhelbergen** [comment]
Fixed in #105.
