### ISSUE TITLE
Remove XYZ is deprecated message regarding session

### ISSUE THREAD

**Issue by bw-allardvanhelbergen** [bw-allardvanhelbergen/go#33]
Session middle ware is giving XYZ is deprecated notices to the console. 
Figure out what's going on.

```
14:32:42 web.1 |  Tue, 21 Apr 2015 13:32:42 GMT express-session deprecated undefined resave option; provide resave option at index.js:61:9
14:32:42 web.1 |  Tue, 21 Apr 2015 13:32:42 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:61:9
14:32:42 web.1 |  Warning: connect.session() MemoryStore is not
14:32:42 web.1 |  designed for a production environment, as it will leak
14:32:42 web.1 |  memory, and will not scale past a single process.
```

**Comment by bw-allardvanhelbergen** [comment]
Fixed first two messages.

Third message requires adding a whole new store which is out of scope of this bug and has been moved to #58.
